sudo: required
dist: trusty

before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic

install: npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test-ci
  - npm run ionic:build

deploy:
  provider: script
  script: ./.travis/deploy.sh
  skip_cleanup: true
  on:
    repo: Manduro/onontdekt
    branch: master
