sudo: required
dist: trusty
language: node_js

node_js:
  - "node"

before_install:
  - npm install -g cordova ionic

install: npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run ionic:build

deploy:
  provider: script
  script: ./scripts/ci/deploy.sh
  skip_cleanup: true
  on:
    repo: Manduro/onontdekt
    branch: master
