sudo: required
dist: trusty
language: node_js

cache:
  directories:
    - "node_modules"

install: npm install

# before_script:
#   - export CHROME_BIN=chromium-browser
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

script:
  - npm run ci

deploy:
  provider: script
  script: ./scripts/ci/deploy.sh
  skip_cleanup: true
  on:
    repo: csrdelft/onontdekt
    branch: master
