sudo: required
dist: trusty

notifications:
  email: true

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - nvm use 4.1.2
  - npm install -g cordova ionic@2.0.0

install: npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build

deploy:
  provider: script
  script: ./.travis/deploy.sh
  skip_cleanup: true
  on:
    repo: Manduro/onontdekt
    branch: master
